site_name: Hobbits
nav:
  - Overview: index.md
  - User Guide: user-guide.md
  - Plugin Developer Guide: plugin-developer-guide.md
theme: readthedocs

remote_branch: master

extra_javascript:
  - js/youtube.js

copyright: 2020 Mahlet, Inc.
